sudo: false
language: node_js
node_js:
  - '12'
cache:
  directories:
    - '$HOME/.npm'
after_success:
  - npm run cov:send
  - npm run cov:check
  - npm run dist
addons:
  ssh_known_hosts: stevenzps.duckdns.org
before_deploy:
  - openssl aes-256-cbc -K $encrypted_2e936ba8e06e_key -iv $encrypted_2e936ba8e06e_iv
    -in selfhost.enc -out ./selfhost -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./selfhost
  - ssh-add ./selfhost
deploy:
  provider: script
  skip_cleanup: true
  script: sh ./deploy.sh
  on:
    branch: master
