sudo: false
language: node_js
node_js:
  - '12'
cache:
  directories:
    - "$HOME/.npm"
script:
  - npm run cov:send
  - npm run cov:check
before_deploy:
  - openssl aes-256-cbc -K $encrypted_2e936ba8e06e_key -iv $encrypted_2e936ba8e06e_iv
    -in selfhost.enc -out ./selfhost -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./selfhost
  - ssh-add ./selfhost
deploy:
  provider: script
  skip_cleanup: true
  script: ssh szh10000@stevenzps.duckdns.org -i ./selfhost ls
  on:
    branch: master
