on:
  push:
    branches:
      - "master"
  workflow_dispatch:

env:
  NODE_VERSION: '12.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run test
        npm run dist
        npm run cov:send

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Prod'

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: app
